# -*- coding: utf-8 -*-
"""reading orca out data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KE0hzDK2uH2Qd7beePg68CYIGn77XYl
"""

import numpy as np

def find_orbitals(filename):
  with open(filename, "r") as f:
    orbitals = []
    inner_orbitals = []
    parse = False
    for line in f:
      #start exctract text 
      if 'ORBITAL ENERGIES' in line:
        parse = True
        next(f)
        next(f)
        continue
                  
      if parse:
        if len(line.split()) == 0:
          orbitals.append(inner_orbitals)
          inner_orbitals = []
          break
        else:
          inner_orbitals.append(line)

  return orbitals[-1]

  def Extract(i, lst):
    return [item[i] for item in lst]

def clean_data(filename):
  orbital_list = find_orbitals(filename)
  rows = []

  for x in range(1, len(orbital_list)):
    rows.append(orbital_list[x].split())

  data = np.array(rows)

  no = Extract(0, data)
  occ = Extract(1, data)
  eeh = Extract(2, data)
  eev = Extract(3, data)

  dict = {'NO': no, 'OCC': occ, 'E(Eh)': eeh, 'E(eV)': eev} 

  df = pd.DataFrame(dict) 
      

  return df

